[profile.default]
src = "src"
out = "out"
libs = ["dependencies"]
solc_version = "0.8.25"
fs_permissions = [
    {access = "read-write", path = "./deployments/anvil.json"},
]

[dependencies]
forge-std = "1.10.0"
"@openzeppelin-contracts" = "5.4.0"


[lint]
exclude_lints = ["mixed-case-function", "unaliased-plain-import", "mixed-case-variable"]

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
